In [119]:
import pandas as pd

df=pd.read_csv("diabetes_risk.csv")

In [120]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                15000 non-null  int64
 1   age                       15000 non-null  int64
 2   gender                    15000 non-null  object
 3   city                      15000 non-null  object
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  object
 6   physical_activity_level   15000 non-null  object
 7   diet_type                 15000 non-null  object
 8   smoking_status            14528 non-null  object
 9   alcohol_consumption       11212 non-null  object
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64
 12  fasting_blood_sugar       15000 non-null  int64
 13  hba1c_level               15000 non-null  float64
 14  blood_pressure_systolic   15000 non-null  int64
 15  blood_pressure_diastolic  15000 non-null  int64
 16  waist_circumference_cm    15000 non-null  float64
 17  income_bracket            14537 non-null  object
 18  diabetes_risk             15000 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 2.2+ MB

In [122]:
df.shape

(15000, 19)

In [123]:
df.describe()

,patient_id,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,44.333667,23.062260,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933
std,4330.271354,10.383753,4.046391,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331
min,1.000000,18.000000,15.000000,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000
25%,3750.750000,38.000000,20.100000,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000
50%,7500.500000,45.000000,22.700000,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000
75%,11250.250000,52.000000,25.600000,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000
max,15000.000000,80.000000,40.800000,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000

In [124]:
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [125]:
y

0        0
1        0
2        2
3        0
4        0
        ..
14995    2
14996    0
14997    0
14998    0
14999    1
Name: diabetes_risk, Length: 15000, dtype: int64

In [126]:
for col in df.select_dtypes(include='object').columns:
    df[col]=df[col].fillna(df[col].mode()[0])

In [127]:
X=df.drop(['diabetes_risk','patient_id'],axis=1)
y=df['diabetes_risk']

In [128]:
X=pd.get_dummies(X,columns=X.select_dtypes(include='object').columns)
y=y.map({'Low':0,'Moderate':1,'High':2})

In [129]:
X

,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,gender_Female,...,diet_type_Vegetarian,smoking_status_Current,smoking_status_Former,smoking_status_Never,alcohol_consumption_Never,alcohol_consumption_Occasional,alcohol_consumption_Regular,income_bracket_High,income_bracket_Low,income_bracket_Middle
0,47,26.5,9.0,8,178,7.3,146,90,107.1,True,...,True,False,False,True,True,False,False,True,False,False
1,53,20.5,7.0,6,152,6.9,156,100,93.8,True,...,True,False,False,True,True,False,False,False,True,False
2,47,31.3,7.0,7,168,6.6,150,102,113.5,False,...,False,True,False,False,False,False,True,False,True,False
3,41,22.8,9.0,5,155,6.7,126,92,109.6,False,...,False,False,False,True,True,False,False,False,False,True
4,57,16.7,6.5,10,188,6.7,130,90,80.8,True,...,False,True,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,47,37.7,6.8,7,213,8.1,150,100,141.7,False,...,False,False,False,True,True,False,False,True,False,False
14996,48,20.6,6.0,8,162,6.5,132,80,91.0,True,...,False,False,False,True,True,False,False,False,False,True
14997,34,17.9,7.0,6,137,6.5,136,90,88.8,True,...,True,False,False,True,True,False,False,False,True,False
14998,56,20.7,6.0,5,163,6.9,140,87,94.8,False,...,True,False,False,True,True,False,False,False,True,False
14999,54,34.5,7.4,2,186,7.2,150,88,130.4,False,...,True,False,False,True,True,False,False,False,False,True

In [130]:
y

0        0
1        0
2        2
3        0
4        0
        ..
14995    2
14996    0
14997    0
14998    0
14999    1
Name: diabetes_risk, Length: 15000, dtype: int64

In [131]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [132]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12000, 48)
(3000, 48)
(12000,)
(3000,)

In [133]:
#now scale the x
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [134]:
import torch 
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)

y_train_tensor=torch.tensor(y_train.values.squeeze(),dtype=torch.long)
y_test_tensor=torch.tensor(y_test.values.squeeze(),dtype=torch.long)

In [135]:
print(X_train_tensor.shape)
print(X_test_tensor.shape)
print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([12000, 48])
torch.Size([3000, 48])
torch.Size([12000])
torch.Size([3000])

In [136]:
from torch.utils.data import DataLoader,Dataset
class customdataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [137]:
train_dataset=customdataset(X_train_tensor,y_train_tensor)
test_dataset=customdataset(X_test_tensor,y_test_tensor)

Create a class called MyModel that inherits from PyTorch's nn.Module. When I create a MyModel object, input_dim tells it how many input features there are, and super().__init__() initializes the parent nn.Module.

In [138]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

In [139]:
import torch.nn as nn

In [140]:
class mynn(nn.Module):
    def __init__(self,input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_layer):
        super().__init__()

        layers=[]

        for i in range(num_hidden_layers):
            layers.append(nn.Linear(input_dim,neurons_per_layer))
            layers.append(nn.BatchNorm1d(neurons_per_layer))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout_layer))

            input_dim=neurons_per_layer

        layers.append(nn.Linear(neurons_per_layer,output_dim))

        self.model=nn.Sequential(*layers)

    def forward(self,x):
        return self.model(x)

In [141]:
def objective(trial):
    
    num_hidden_layers=trial.suggest_int("num_hidden_layer",1,5)
    neurons_per_layer=trial.suggest_int("neurons_per_layer",8,128,step=8)
    epochs=trial.suggest_int("num_of_eopochs",10,50,step=10)
    dropout_layer=trial.suggest_float("dropout_layer",1e-5,1e-3,log=True)
    weight_decay=trial.suggest_float("weight_decays",1e-5,1e-3,log=True)
    optimizer_names=trial.suggest_categorical("optimizer_names",["Adam","SGD","RMSprop"])
    learning_rate=trial.suggest_float("learning_rate",1e-5,1e-1,log=True)
    batch_size=trial.suggest_categorical("batch_size",[8,16,32,64])
    
    train_loader=DataLoader(train_dataset,batch_size=batch_size,shuffle=True)
    test_loader=DataLoader(test_dataset,batch_size=batch_size,shuffle=False)

    input_dim=48
    output_dim=3

    model=mynn(input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_layer)

    criterion=nn.CrossEntropyLoss()
    if optimizer_names=="Adam":
        optimizer=optim.Adam(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
    elif optimizer_names=="SGD":
        optimizer=optim.SGD(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
    else:
        optimizer=optim.RMSprop(model.parameters(),lr=learning_rate,weight_decay=weight_decay)

    
    for epoch in range(epochs):
        for batch_features,batch_labels in train_loader:
            output=model(batch_features)
            loss=criterion(output,batch_labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
    model.eval()
    total=0
    correct=0

    with torch.no_grad():
        for batch_features,batch_labels in test_loader:
            output=model(batch_features)
            __,predicted=torch.max(output,1)
            total=total+batch_labels.shape[0]
            correct=correct+(predicted==batch_labels).sum().item()
    accuracy=correct/total
    return accuracy

In [142]:
import optuna

study=optuna.create_study(direction='maximize')

[I 2026-09-06 12:26:24,841] A new study created in memory with name: no-name-1ab59e15-b438-453a-b808-72b16cf9f4fe

In [143]:
study.optimize(objective,n_trials=5)

[I 2026-09-06 12:27:13,540] Trial 0 finished with value: 0.607 and parameters: {'num_hidden_layer': 3, 'neurons_per_layer': 8, 'num_of_eopochs': 10, 'dropout_layer': 0.00019998407383726432, 'weight_decays': 0.0001631173661779918, 'optimizer_names': 'Adam', 'learning_rate': 1.0962550613556964e-05, 'batch_size': 16}. Best is trial 0 with value: 0.607.
[I 2026-09-06 12:27:44,335] Trial 1 finished with value: 0.7926666666666666 and parameters: {'num_hidden_layer': 3, 'neurons_per_layer': 32, 'num_of_eopochs': 20, 'dropout_layer': 0.0003156035869085302, 'weight_decays': 0.0005703735449225566, 'optimizer_names': 'Adam', 'learning_rate': 0.004722288616127819, 'batch_size': 64}. Best is trial 1 with value: 0.7926666666666666.
[I 2026-09-06 12:28:24,404] Trial 2 finished with value: 0.6056666666666667 and parameters: {'num_hidden_layer': 1, 'neurons_per_layer': 64, 'num_of_eopochs': 30, 'dropout_layer': 8.452426441486027e-05, 'weight_decays': 3.139681139703794e-05, 'optimizer_names': 'SGD', 'learning_rate': 2.6669583551345946e-05, 'batch_size': 32}. Best is trial 1 with value: 0.7926666666666666.
[I 2026-09-06 12:29:40,083] Trial 3 finished with value: 0.7903333333333333 and parameters: {'num_hidden_layer': 3, 'neurons_per_layer': 32, 'num_of_eopochs': 50, 'dropout_layer': 0.00014322963824811412, 'weight_decays': 9.205563804433221e-05, 'optimizer_names': 'Adam', 'learning_rate': 0.09619450242357806, 'batch_size': 64}. Best is trial 1 with value: 0.7926666666666666.
[I 2026-09-06 12:31:34,439] Trial 4 finished with value: 0.6433333333333333 and parameters: {'num_hidden_layer': 1, 'neurons_per_layer': 120, 'num_of_eopochs': 50, 'dropout_layer': 3.582367438254163e-05, 'weight_decays': 9.59589473285627e-05, 'optimizer_names': 'SGD', 'learning_rate': 2.069681295991944e-05, 'batch_size': 16}. Best is trial 1 with value: 0.7926666666666666.

In [144]:
print("Best Accuracy:", study.best_value)
print("Best Parameters:", study.best_params)

Best Accuracy: 0.7926666666666666
Best Parameters: {'num_hidden_layer': 3, 'neurons_per_layer': 32, 'num_of_eopochs': 20, 'dropout_layer': 0.0003156035869085302, 'weight_decays': 0.0005703735449225566, 'optimizer_names': 'Adam', 'learning_rate': 0.004722288616127819, 'batch_size': 64}