In [1]:
import pandas as pd

df=pd.read_csv("diabetes_risk.csv")

In [2]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                15000 non-null  int64
 1   age                       15000 non-null  int64
 2   gender                    15000 non-null  object
 3   city                      15000 non-null  object
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  object
 6   physical_activity_level   15000 non-null  object
 7   diet_type                 15000 non-null  object
 8   smoking_status            14528 non-null  object
 9   alcohol_consumption       11212 non-null  object
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64
 12  fasting_blood_sugar       15000 non-null  int64
 13  hba1c_level               15000 non-null  float64
 14  blood_pressure_systolic   15000 non-null  int64
 15  blood_pressure_diastolic  15000 non-null  int64
 16  waist_circumference_cm    15000 non-null  float64
 17  income_bracket            14537 non-null  object
 18  diabetes_risk             15000 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 2.2+ MB

In [4]:
df.shape

(15000, 19)

In [5]:
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [6]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [7]:
df.isnull().sum()

patient_id                  0
age                         0
gender                      0
city                        0
bmi                         0
family_history_diabetes     0
physical_activity_level     0
diet_type                   0
smoking_status              0
alcohol_consumption         0
hours_sleep_per_night       0
stress_level                0
fasting_blood_sugar         0
hba1c_level                 0
blood_pressure_systolic     0
blood_pressure_diastolic    0
waist_circumference_cm      0
income_bracket              0
diabetes_risk               0
dtype: int64

In [8]:
X=df.drop(["patient_id","diabetes_risk"],axis=1)
y=df["diabetes_risk"]

In [9]:
y

0             Low
1             Low
2            High
3             Low
4             Low
           ...
14995        High
14996         Low
14997         Low
14998         Low
14999    Moderate
Name: diabetes_risk, Length: 15000, dtype: object

In [10]:
X

,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket
0,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High
1,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low
2,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low
3,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle
4,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,47,Male,Mumbai,37.7,No,Sedentary,Non-Vegetarian,Never,Never,6.8,7,213,8.1,150,100,141.7,High
14996,48,Female,Mumbai,20.6,No,Moderate,Non-Vegetarian,Never,Never,6.0,8,162,6.5,132,80,91.0,Middle
14997,34,Female,Nagpur,17.9,No,Active,Vegetarian,Never,Never,7.0,6,137,6.5,136,90,88.8,Low
14998,56,Male,Ahmedabad,20.7,Yes,Active,Vegetarian,Never,Never,6.0,5,163,6.9,140,87,94.8,Low
14999,54,Male,Surat,34.5,No,Moderate,Vegetarian,Never,Never,7.4,2,186,7.2,150,88,130.4,Middle

In [11]:
#encode the categorical columns using one hot encoding
X = pd.get_dummies(X, columns=X.select_dtypes(include='object').columns)
#y with label encoding
y = y.map({'Low': 0, 'Moderate':1,'High': 2})

In [12]:
#train test split the data now
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(X_train.mean())
print(X_train.std())

(12000, 48)
(3000, 48)
(12000,)
(3000,)
age                                   44.374333
bmi                                   23.078067
hours_sleep_per_night                  7.305067
stress_level                           5.954417
fasting_blood_sugar                  168.887250
hba1c_level                            6.881967
blood_pressure_systolic              139.556083
blood_pressure_diastolic              86.261667
waist_circumference_cm               100.251942
gender_Female                          0.481750
gender_Male                            0.508333
gender_Other                           0.009917
city_Ahmedabad                         0.069500
city_Bengaluru                         0.101000
city_Bhopal                            0.025083
city_Chennai                           0.063583
city_Delhi                             0.115833
city_Hyderabad                         0.082000
city_Indore                            0.029917
city_Jaipur                            0.041083
city_Kanpur                            0.031833
city_Kolkata                           0.058917
city_Lucknow                           0.030417
city_Mumbai                            0.151667
city_Nagpur                            0.030833
city_Patna                             0.018250
city_Pune                              0.051250
city_Surat                             0.049333
city_Thane                             0.029250
city_Visakhapatnam                     0.020250
family_history_diabetes_No             0.649917
family_history_diabetes_Yes            0.350083
physical_activity_level_Active         0.339583
physical_activity_level_Moderate       0.330917
physical_activity_level_Sedentary      0.329500
diet_type_Non-Vegetarian               0.549250
diet_type_Pescatarian                  0.029500
diet_type_Vegan                        0.020000
diet_type_Vegetarian                   0.401250
smoking_status_Current                 0.195833
smoking_status_Former                  0.099917
smoking_status_Never                   0.704250
alcohol_consumption_Never              0.622667
alcohol_consumption_Occasional         0.303583
alcohol_consumption_Regular            0.073750
income_bracket_High                    0.255833
income_bracket_Low                     0.226083
income_bracket_Middle                  0.518083
dtype: float64
age                                  10.414945
bmi                                   4.046591
hours_sleep_per_night                 1.103043
stress_level                          2.152686
fasting_blood_sugar                  38.313401
hba1c_level                           0.844113
blood_pressure_systolic              12.617116
blood_pressure_diastolic              8.383986
waist_circumference_cm               10.751506
gender_Female                         0.499688
gender_Male                           0.499951
gender_Other                          0.099092
city_Ahmedabad                        0.254313
city_Bengaluru                        0.301341
city_Bhopal                           0.156385
city_Chennai                          0.244019
city_Delhi                            0.320038
city_Hyderabad                        0.274376
city_Indore                           0.170365
city_Jaipur                           0.198491
city_Kanpur                           0.175563
city_Kolkata                          0.235478
city_Lucknow                          0.171738
city_Mumbai                           0.358712
city_Nagpur                           0.172873
city_Patna                            0.133860
city_Pune                             0.220516
city_Surat                            0.216572
city_Thane                            0.168514
city_Visakhapatnam                    0.140860
family_history_diabetes_No            0.477016
family_history_diabetes_Yes           0.477016
physical_activity_level_Active        0.473588
physical_activity_level_Moderate      0.470563
physical_activity_level_Sedentary     0.470051
diet_type_Non-Vegetarian              0.497589
diet_type_Pescatarian                 0.169210
diet_type_Vegan                       0.140006
diet_type_Vegetarian                  0.490172
smoking_status_Current                0.396857
smoking_status_Former                 0.299901
smoking_status_Never                  0.456398
alcohol_consumption_Never             0.484740
alcohol_consumption_Occasional        0.459824
alcohol_consumption_Regular           0.261375
income_bracket_High                   0.436347
income_bracket_Low                    0.418311
income_bracket_Middle                 0.499694
dtype: float64

In [14]:
#scale the data now x is multiple data and also it is scaleble and y is only 3 classes which is already scale
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.transform(X_test)

In [15]:
#now convert to tensors

import torch

x_train_tensor=torch.tensor(x_train_scaled,dtype=torch.float32)
x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)

y_train_tensor=torch.tensor(y_train.values.squeeze(),dtype=torch.long)
y_test_tensor=torch.tensor(y_test.values.squeeze(),dtype=torch.long)

In [16]:
print(x_train_tensor.shape)
print(x_test_tensor.shape)
print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([12000, 48])
torch.Size([3000, 48])
torch.Size([12000])
torch.Size([3000])

In [17]:
#define customdataset
from torch.utils.data import Dataset,DataLoader
class customdataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [18]:
#make train dataset now from xtrain and y train and testsxy
train_dataset=customdataset(x_train_tensor,y_train_tensor)
test_dataset=customdataset(x_test_tensor,y_test_tensor)

Linear(10,64)
BatchNorm1d(64)
ReLU()
Dropout(0.2)

Linear(64,64)
BatchNorm1d(64)
ReLU()
Dropout(0.2)

Linear(64,64)
BatchNorm1d(64)
ReLU()
Dropout(0.2)

In [19]:
import torch.nn as nn

class mynn(nn.Module):
    def __init__(self,input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_layer):
        super().__init__()

        layers=[]

        for i in range(num_hidden_layers):
            layers.append(nn.Linear(input_dim,neurons_per_layer))
            layers.append(nn.BatchNorm1d(neurons_per_layer))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout_layer))
            
            input_dim=neurons_per_layer

        layers.append(nn.Linear(neurons_per_layer,output_dim))

        self.model=nn.Sequential(*layers)

    def forward(self,x):
        return self.model(x)

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

In [21]:
#objective function where the hyperparameter to be what slected the best 
def objective(trial):

    num_hidden_layers=trial.suggest_int("num_hidden_layers",1,5)
    neurons_per_layer=trial.suggest_int("neurons_per_layer",8,128,step=8)
    epochs=trial.suggest_int("num_of_epochs",10,50,step=10)
    learning_rate=trial.suggest_float("learing_rate",1e-5,1e-1,log=True)
    dropout_layer=trial.suggest_float("dropout_rate",0.1,0.5,step=0.1)
    batch_size = trial.suggest_categorical("batch_size",[16, 32, 64, 128])
    optimizer_name=trial.suggest_categorical("optimizer_name",["Adam","SGD","RMSprop"])
    weight_decay=trial.suggest_float("weight_decay",1e-5,1e-3,log=True)

    train_loader=DataLoader(train_dataset,batch_size=batch_size,shuffle=True)
    test_loader=DataLoader(test_dataset,batch_size=batch_size,shuffle=False)

    input_dim=X_train.shape[1]
    output_dim=3

    model=mynn(input_dim,output_dim,num_hidden_layers,neurons_per_layer,dropout_layer)

    #optimizer selcetion

    criterion=nn.CrossEntropyLoss()
    if optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(),lr=learning_rate,weight_decay=weight_decay)

    elif optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(),lr=learning_rate,weight_decay=weight_decay)

    else:
        optimizer = optim.RMSprop(model.parameters(),lr=learning_rate,weight_decay=weight_decay)
    
    #training loop

    for epoch in range(epochs):
        for batch_features,batch_labels in train_loader:
            #forward pass
            output=model(batch_features)
            #calculate loss
            loss=criterion(output,batch_labels)

            #backward pass
            optimizer.zero_grad()
            loss.backward()

            #update grads
            optimizer.step()

#evaluation
    model.eval()
#evaluation on test data

    total=0
    correct=0

    with torch.no_grad():
        for batch_features,batch_labels in test_loader:
            output=model(batch_features)
            __,predicted=torch.max(output,1)

            total=total+batch_labels.shape[0]
            correct=correct+(predicted==batch_labels).sum().item()
    accuracy=correct/total
    return accuracy

In [22]:
import optuna

study=optuna.create_study(direction='maximize')

c:\Users\Furqan Khan\AppData\Local\miniconda3\envs\agent_env2\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-09-07 11:16:12,847] A new study created in memory with name: no-name-106f514d-37d4-48d2-bc54-511d78cba962

In [23]:
study.optimize(objective,n_trials=5)

[I 2026-09-07 11:16:20,166] Trial 0 finished with value: 0.31266666666666665 and parameters: {'num_hidden_layers': 2, 'neurons_per_layer': 40, 'num_of_epochs': 10, 'learing_rate': 6.087048796835148e-05, 'dropout_rate': 0.1, 'batch_size': 128, 'optimizer_name': 'SGD', 'weight_decay': 6.655511929241799e-05}. Best is trial 0 with value: 0.31266666666666665.
[I 2026-09-07 11:16:27,943] Trial 1 finished with value: 0.7673333333333333 and parameters: {'num_hidden_layers': 2, 'neurons_per_layer': 64, 'num_of_epochs': 10, 'learing_rate': 0.001579988950635341, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer_name': 'SGD', 'weight_decay': 0.0003438075152022534}. Best is trial 1 with value: 0.7673333333333333.
[I 2026-09-07 11:17:05,569] Trial 2 finished with value: 0.7896666666666666 and parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 88, 'num_of_epochs': 20, 'learing_rate': 0.00029244374240216403, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer_name': 'Adam', 'weight_decay': 0.0003950572478444533}. Best is trial 2 with value: 0.7896666666666666.
[I 2026-09-07 11:17:41,793] Trial 3 finished with value: 0.777 and parameters: {'num_hidden_layers': 3, 'neurons_per_layer': 104, 'num_of_epochs': 30, 'learing_rate': 0.01871239688991381, 'dropout_rate': 0.5, 'batch_size': 32, 'optimizer_name': 'RMSprop', 'weight_decay': 1.2816340421680884e-05}. Best is trial 2 with value: 0.7896666666666666.
[I 2026-09-07 11:18:00,452] Trial 4 finished with value: 0.7726666666666666 and parameters: {'num_hidden_layers': 1, 'neurons_per_layer': 32, 'num_of_epochs': 30, 'learing_rate': 0.0007337348029964257, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer_name': 'SGD', 'weight_decay': 1.3824426533488097e-05}. Best is trial 2 with value: 0.7896666666666666.

In [24]:
print("Best Accuracy:", study.best_value)
print("Best Parameters:", study.best_params)

Best Accuracy: 0.7896666666666666
Best Parameters: {'num_hidden_layers': 4, 'neurons_per_layer': 88, 'num_of_epochs': 20, 'learing_rate': 0.00029244374240216403, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer_name': 'Adam', 'weight_decay': 0.0003950572478444533}